name: github-pages
on:
  workflow_run:
    branches: [main]
    workflows: [test]
    types: [completed]
jobs:
  main:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    container: node:lts-alpine@sha256:21f403ab171f2dc89bad4dd69d7721bfd15f084ccb46cdd225f31f2bc59b5c9a
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "lts/*"
          cache: npm
      - name: Build
        run: |
          apk add mdbook tar
          npm ci
          npm run build
          mdbook build
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: book
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
