name: github-pages
on:
  workflow_run:
    branches: [main]
    workflows: [test]
    types: [completed]
jobs:
  main:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    container: node:lts-alpine@sha256:156b55f92e98ccd5ef49578a8cea0df4679826564bad1c9d4ef04462b9f0ded6
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "lts/*"
          cache: npm
      - name: Build
        run: |
          apk add mdbook tar
          npm ci
          npm run build
          mdbook build
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: book
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
